@startuml
actor Student

Student -> Catalogue : GUI
activate Catalogue

Catalogue -> "Didactic Personal" : GET /professors?studentCode={code}&year={year}
activate "Didactic Personal"
activate "DB"
"Didactic Personal" -> "DB"
"DB" --> "Didactic Personal": Extract List<Professor>

"Didactic Personal" --> Catalogue : List<Professor>
deactivate "Didactic Personal"

Catalogue --> Student : List<Professor>
deactivate Catalogue
@enduml
