CREATE TABLE CATALOGUE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CODE VARCHAR(50) UNIQUE NOT NULL,
    CLASS_CODE VARCHAR(50),
    CATALOGUE_YEAR INT
);

CREATE TABLE SEMESTER (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CATALOGUE_ID BIGINT NOT NULL,
    FOREIGN KEY (catalogue_id) REFERENCES catalogue(id) ON DELETE CASCADE
);

CREATE TABLE STUDENT (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    cat_code VARCHAR(50) NOT NULL,
    code VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE DISCIPLINE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE GRADE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    semester_id BIGINT NOT NULL,
    discipline_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    professor_code VARCHAR(50) NOT NULL,
    grade_value DECIMAL(5,2) NOT NULL,
    date DATE,
    FOREIGN KEY (semester_id) REFERENCES semester(id) ON DELETE CASCADE,
    FOREIGN KEY (discipline_id) REFERENCES discipline(id) ON DELETE CASCADE,
    FOREIGN KEY (student_id) REFERENCES student(id) ON DELETE CASCADE
);
